### ISSUE TITLE
New Update Broke Bot

### ISSUE THREAD

**Issue by dannymichel** [JesseStorms/docker_modmailbot#1]
```
Starting Modmail 3.4.1 on Node.js 16.15.0 (x64)
Loading configuration from config.json...
Configuration ok!
Using an SQLite database:
  /bot/db/data.sqlite
Knex: run
$ npm install sqlite3 --save
Cannot find module '/bot/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-x64/node_sqlite3.node'
Require stack:
- /bot/node_modules/sqlite3/lib/sqlite3-binding.js
- /bot/node_modules/sqlite3/lib/sqlite3.js
- /bot/node_modules/knex/lib/dialects/sqlite3/index.js
- /bot/node_modules/knex/lib/dialects/index.js
- /bot/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /bot/node_modules/knex/lib/knex-builder/Knex.js
- /bot/node_modules/knex/lib/index.js
- /bot/node_modules/knex/knex.js
- /bot/src/knex.js
- /bot/src/main.js
- /bot/src/index.js
Error: Cannot find module '/bot/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-x64/node_sqlite3.node'
Require stack:
- /bot/node_modules/sqlite3/lib/sqlite3-binding.js
- /bot/node_modules/sqlite3/lib/sqlite3.js
- /bot/node_modules/knex/lib/dialects/sqlite3/index.js
- /bot/node_modules/knex/lib/dialects/index.js
- /bot/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /bot/node_modules/knex/lib/knex-builder/Knex.js
- /bot/node_modules/knex/lib/index.js
- /bot/node_modules/knex/knex.js
- /bot/src/knex.js
- /bot/src/main.js
- /bot/src/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/bot/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
Error: Error: Knex: run
$ npm install sqlite3 --save
Cannot find module '/bot/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-x64/node_sqlite3.node'
Require stack:
- /bot/node_modules/sqlite3/lib/sqlite3-binding.js
- /bot/node_modules/sqlite3/lib/sqlite3.js
- /bot/node_modules/knex/lib/dialects/sqlite3/index.js
- /bot/node_modules/knex/lib/dialects/index.js
    ...stack trace truncated to 8 lines
npm notice 
npm notice New minor version of npm available! 8.5.5 -> 8.12.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.12.0>
npm notice Run `npm install -g npm@8.12.0` to update!
npm notice 
Starting Modmail 3.4.1 on Node.js 16.15.0 (x64)
Loading configuration from config.json...
Configuration ok!
Using an SQLite database:
  /bot/db/data.sqlite
Knex: run
$ npm install sqlite3 --save
Cannot find module '/bot/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-x64/node_sqlite3.node'
Require stack:
- /bot/node_modules/sqlite3/lib/sqlite3-binding.js
- /bot/node_modules/sqlite3/lib/sqlite3.js
- /bot/node_modules/knex/lib/dialects/sqlite3/index.js
- /bot/node_modules/knex/lib/dialects/index.js
- /bot/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /bot/node_modules/knex/lib/knex-builder/Knex.js
- /bot/node_modules/knex/lib/index.js
- /bot/node_modules/knex/knex.js
- /bot/src/knex.js
- /bot/src/main.js
- /bot/src/index.js
Error: Cannot find module '/bot/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-x64/node_sqlite3.node'
Require stack:
- /bot/node_modules/sqlite3/lib/sqlite3-binding.js
- /bot/node_modules/sqlite3/lib/sqlite3.js
- /bot/node_modules/knex/lib/dialects/sqlite3/index.js
- /bot/node_modules/knex/lib/dialects/index.js
- /bot/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /bot/node_modules/knex/lib/knex-builder/Knex.js
- /bot/node_modules/knex/lib/index.js
- /bot/node_modules/knex/knex.js
- /bot/src/knex.js
- /bot/src/main.js
- /bot/src/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/bot/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
Error: Error: Knex: run
$ npm install sqlite3 --save
Cannot find module '/bot/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-x64/node_sqlite3.node'
Require stack:
- /bot/node_modules/sqlite3/lib/sqlite3-binding.js
- /bot/node_modules/sqlite3/lib/sqlite3.js
- /bot/node_modules/knex/lib/dialects/sqlite3/index.js
- /bot/node_modules/knex/lib/dialects/index.js
    ...stack trace truncated to 8 lines
Starting Modmail 3.4.1 on Node.js 16.15.0 (x64)
Loading configuration from config.json...
Configuration ok!
Using an SQLite database:
  /bot/db/data.sqlite
Knex: run
$ npm install sqlite3 --save
Cannot find module '/bot/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-x64/node_sqlite3.node'
Require stack:
- /bot/node_modules/sqlite3/lib/sqlite3-binding.js
- /bot/node_modules/sqlite3/lib/sqlite3.js
- /bot/node_modules/knex/lib/dialects/sqlite3/index.js
- /bot/node_modules/knex/lib/dialects/index.js
- /bot/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /bot/node_modules/knex/lib/knex-builder/Knex.js
- /bot/node_modules/knex/lib/index.js
- /bot/node_modules/knex/knex.js
- /bot/src/knex.js
- /bot/src/main.js
- /bot/src/index.js
Error: Cannot find module '/bot/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-x64/node_sqlite3.node'
Require stack:
- /bot/node_modules/sqlite3/lib/sqlite3-binding.js
- /bot/node_modules/sqlite3/lib/sqlite3.js
- /bot/node_modules/knex/lib/dialects/sqlite3/index.js
- /bot/node_modules/knex/lib/dialects/index.js
- /bot/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /bot/node_modules/knex/lib/knex-builder/Knex.js
- /bot/node_modules/knex/lib/index.js
- /bot/node_modules/knex/knex.js
- /bot/src/knex.js
- /bot/src/main.js
- /bot/src/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/bot/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
Error: Error: Knex: run
$ npm install sqlite3 --save
Cannot find module '/bot/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-x64/node_sqlite3.node'
Require stack:
- /bot/node_modules/sqlite3/lib/sqlite3-binding.js
- /bot/node_modules/sqlite3/lib/sqlite3.js
- /bot/node_modules/knex/lib/dialects/sqlite3/index.js
- /bot/node_modules/knex/lib/dialects/index.js
    ...stack trace truncated to 8 lines
Starting Modmail 3.4.1 on Node.js 16.15.0 (x64)
Loading configuration from config.json...
Configuration ok!
Using an SQLite database:
  /bot/db/data.sqlite
Knex: run
$ npm install sqlite3 --save
Cannot find module '/bot/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-x64/node_sqlite3.node'
Require stack:
- /bot/node_modules/sqlite3/lib/sqlite3-binding.js
- /bot/node_modules/sqlite3/lib/sqlite3.js
- /bot/node_modules/knex/lib/dialects/sqlite3/index.js
- /bot/node_modules/knex/lib/dialects/index.js
- /bot/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /bot/node_modules/knex/lib/knex-builder/Knex.js
- /bot/node_modules/knex/lib/index.js
- /bot/node_modules/knex/knex.js
- /bot/src/knex.js
- /bot/src/main.js
- /bot/src/index.js
Error: Cannot find module '/bot/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-x64/node_sqlite3.node'
Require stack:
- /bot/node_modules/sqlite3/lib/sqlite3-binding.js
- /bot/node_modules/sqlite3/lib/sqlite3.js
- /bot/node_modules/knex/lib/dialects/sqlite3/index.js
- /bot/node_modules/knex/lib/dialects/index.js
- /bot/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /bot/node_modules/knex/lib/knex-builder/Knex.js
- /bot/node_modules/knex/lib/index.js
- /bot/node_modules/knex/knex.js
- /bot/src/knex.js
- /bot/src/main.js
- /bot/src/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/bot/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
Error: Error: Knex: run
$ npm install sqlite3 --save
Cannot find module '/bot/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-x64/node_sqlite3.node'
Require stack:
- /bot/node_modules/sqlite3/lib/sqlite3-binding.js
- /bot/node_modules/sqlite3/lib/sqlite3.js
- /bot/node_modules/knex/lib/dialects/sqlite3/index.js
- /bot/node_modules/knex/lib/dialects/index.js
    ...stack trace truncated to 8 lines
Starting Modmail 3.4.1 on Node.js 16.15.0 (x64)
Loading configuration from config.json...
Configuration ok!
Using an SQLite database:
  /bot/db/data.sqlite
Knex: run
$ npm install sqlite3 --save
Cannot find module '/bot/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-x64/node_sqlite3.node'
Require stack:
- /bot/node_modules/sqlite3/lib/sqlite3-binding.js
- /bot/node_modules/sqlite3/lib/sqlite3.js
- /bot/node_modules/knex/lib/dialects/sqlite3/index.js
- /bot/node_modules/knex/lib/dialects/index.js
- /bot/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /bot/node_modules/knex/lib/knex-builder/Knex.js
- /bot/node_modules/knex/lib/index.js
- /bot/node_modules/knex/knex.js
- /bot/src/knex.js
- /bot/src/main.js
- /bot/src/index.js
Error: Cannot find module '/bot/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-x64/node_sqlite3.node'
Require stack:
- /bot/node_modules/sqlite3/lib/sqlite3-binding.js
- /bot/node_modules/sqlite3/lib/sqlite3.js
- /bot/node_modules/knex/lib/dialects/sqlite3/index.js
- /bot/node_modules/knex/lib/dialects/index.js
- /bot/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /bot/node_modules/knex/lib/knex-builder/Knex.js
- /bot/node_modules/knex/lib/index.js
- /bot/node_modules/knex/knex.js
- /bot/src/knex.js
- /bot/src/main.js
- /bot/src/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/bot/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
Error: Error: Knex: run
$ npm install sqlite3 --save
Cannot find module '/bot/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-x64/node_sqlite3.node'
Require stack:
- /bot/node_modules/sqlite3/lib/sqlite3-binding.js
- /bot/node_modules/sqlite3/lib/sqlite3.js
- /bot/node_modules/knex/lib/dialects/sqlite3/index.js
- /bot/node_modules/knex/lib/dialects/index.js
    ...stack trace truncated to 8 lines
    ```

**Comment by JesseStorms** [comment]
Thanks for the heads up, I'll look into it later.

**Comment by JesseStorms** [comment]
Should be fixed, run `docker pull jessestorms/docker_modmailbot:latest` to update
